import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { cn } from "@/lib/utils"
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Navbar/Header";

export const metadata: Metadata = {
  title: "Nicolas Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-[100dvh] bg-background font-sans antialiased flex flex-col",
        inter.className
      )}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
